#!/usr/bin/env python3
"""Generate the complete image with Snakemake, independent of analysis inputs."""
import argparse
import difflib
import hashlib
import json
import os
from pathlib import Path
import re
import shlex
import shutil
import subprocess
import tempfile

ROOT = Path(__file__).resolve().parents[2]
SNAKEMAKE_VERSION = "9.8.0"
BASE_IMAGE = "condaforge/miniforge3:26.1.1-3@sha256:958d2675e9a43e199cc85345ff4c60796236b651a9da4982765d99bd34a682d1"


def generate(root=ROOT, snakemake="snakemake"):
    version = subprocess.check_output([snakemake, "--version"], text=True).strip()
    if version != SNAKEMAKE_VERSION:
        raise ValueError(f"Generate with Snakemake {SNAKEMAKE_VERSION}, found {version}")
    environments = sorted((root / "workflow/envs").glob("*.yaml"))
    if not environments:
        raise ValueError("No workflow environments found")
    # Version 9.8's generator does not apply explicit package pin files.
    # Refuse them instead of silently building a differently resolved image.
    if list((root / "workflow/envs").glob("*.pin.txt")):
        raise ValueError("Snakemake 9.8 containerization does not apply .pin.txt files")
    with tempfile.TemporaryDirectory(prefix="phenoradar-containerize-") as temporary:
        staging = Path(temporary)
        shutil.copytree(root / "workflow/envs", staging / "workflow/envs")
        rules = ["rule all:\n    input: " + repr([f"done/{p.stem}" for p in environments])]
        for index, path in enumerate(environments):
            rules.append(f'''rule environment_{index}:
    output: "done/{path.stem}"
    conda: "workflow/envs/{path.name}"
    shell: "touch {{output}}"
''')
        (staging / "Snakefile").write_text("\n\n".join(rules))
        raw = subprocess.check_output(
            [snakemake, "--snakefile", "Snakefile", "--cores", "1", "--containerize"],
            cwd=staging, text=True,
            env={**os.environ, "XDG_CACHE_HOME": str(staging / ".cache")})
    prefixes = dict(re.findall(
        r"COPY workflow/envs/([\w.-]+)\.yaml (/conda-envs/[0-9a-f]+)/environment.yaml", raw))
    if set(prefixes) != {p.stem for p in environments}:
        raise ValueError("Generated Dockerfile does not include every environment")
    if not raw.startswith("FROM condaforge/miniforge3:latest\n"):
        raise ValueError("Unexpected Snakemake Dockerfile format")
    raw = raw.replace("FROM condaforge/miniforge3:latest", f"FROM {BASE_IMAGE}", 1)
    sources = [*environments, *sorted((root / "workflow/envs").glob("*.post-deploy.sh")),
               root / "workflow/scripts/prepare_phylogeny_tools.py",
               root / "workflow/scripts/common.py", root / "workflow/scripts/generate_container.py"]
    hashes = {str(p.relative_to(root)): hashlib.sha256(p.read_bytes()).hexdigest()
              for p in sources}
    manifest = {"snakemake": version, "base_image": BASE_IMAGE,
                "environments": prefixes, "sources": hashes}
    parts = ["# Generated by workflow/scripts/generate_container.py; do not edit.\n" + raw]
    for path in sorted((root / "workflow/envs").glob("*.post-deploy.sh")):
        name = path.name.removesuffix(".post-deploy.sh")
        prefix = prefixes[name]
        target = f"{prefix}/post-deploy.sh"
        parts.append(f"COPY workflow/envs/{path.name} {target}\n"
                     f"RUN conda run --no-capture-output --prefix {prefix} bash {target}")
    # Reuse the same upstream ASTRAL-IV builder as native Conda installations.
    parts.append("COPY workflow/scripts/prepare_phylogeny_tools.py workflow/scripts/common.py /opt/phenoradar/build/\n"
                 f"RUN conda run --no-capture-output --prefix {prefixes['dating']} "
                 "python /opt/phenoradar/build/prepare_phylogeny_tools.py "
                 "--destination /opt/phenoradar/phylogeny_tools\n"
                 "ENV PHENORADAR_PHYLOGENY_TOOLS=/opt/phenoradar/phylogeny_tools\n"
                 "ENV MPLBACKEND=Agg\n"
                 f"RUN printf '%s\\n' {shlex.quote(json.dumps(manifest, sort_keys=True))} "
                 "> /opt/phenoradar/container.json\n"
                 "RUN command -v findmnt && command -v tar && command -v bash")
    return "\n\n".join(parts).rstrip() + "\n"


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--snakemake", default=os.environ.get("SNAKEMAKE_BIN", "snakemake"))
    parser.add_argument("--check", action="store_true", help="fail if Dockerfile needs regeneration")
    args = parser.parse_args()
    generated = generate(snakemake=args.snakemake)
    destination = ROOT / "Dockerfile"
    if args.check:
        existing = destination.read_text() if destination.exists() else ""
        if generated != existing:
            print("".join(difflib.unified_diff(existing.splitlines(True), generated.splitlines(True),
                                              fromfile="Dockerfile", tofile="regenerated")))
            raise SystemExit("Regenerate Dockerfile with workflow/scripts/generate_container.py")
        print("Dockerfile is current; every workflow environment is included.")
    else:
        destination.write_text(generated)
        print(f"Wrote {destination}")


if __name__ == "__main__":
    main()
